### Author: Frish2021 ###
name: deploy_7.0.0-preview-20250715-01

on:
  push:
    branches: [ "master" ]
    paths:
      - "main/**/*"
      - '.github/workflows/deploy.yml'

permissions: write-all

jobs:
  build:
    name: Build NBT-jar
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4.5.0
      with: 
        java-version: '23'
        distribution: 'zulu'
        architecture: x64

    - name: Chmod Script
      run: chmod +x ./gradlew

    - name: Build Package
      run: chmod +x ./scripts/build.sh && bash ./scripts/build.sh

    - name: Publish Package
      run: chmod +x ./scripts/publish.sh && bash ./scripts/publish.sh
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

    - name: Upload artifacts
      uses: softprops/action-gh-release@v2
      with:
        prerelease: true
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: '7.0.0-preview-20250715-01'
        name: 'NBT-7.0.0-preview-20250715-01'
        files: |
          target/**
          LICENSE.md
