### Author: Frish2021 ###
name: publish

on:
  workflow_dispatch:

jobs:
  build:
    name: Publish NBT-Jar
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4.5.0
      with:
        java-version: '8'
        distribution: 'temurin'
        architecture: x64

    - name: Publish package
      run: chmod +x ./scripts/publish.sh && bash ./scripts/publish.sh
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
