### Author: Frish2021 ###
name: publish

on:
  release:
    types: [ created ]

jobs:
  build:
    name: Publishing NBT to maven.
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4.5.0
      with:
        java-version: '22'
        distribution: 'temurin'
        architecture: x64

    - name: Publish package
      run: ./gradlew publish
      env:
        GITHUB_TOKEN: ${{ secrets.CREATE_RELEASE }}
