### Author: Frish2021 ###
name: release

on:
  workflow_dispatch:

jobs:
  build:
    name: Build NBT-jar
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4.5.0
      with: 
        java-version: '8'
        distribution: 'temurin'
        architecture: x64

    - name: Build Jar!
      run: chmod +x ./scripts/build.sh && bash ./scripts/build.sh

    - name: Upload artifacts
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.CREATE_RELEASE }}
        tag_name: '${{ secrets.VERSION }}'
        name: 'NBT-${{ secrets.VERSION }}'
        files: 'target/**'
