### Author: Frish2021 ###
name: release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: A version input.

jobs:
  build:
    name: Build NBT-jar
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4.5.0
      with: 
        java-version: '8'
        distribution: 'temurin'
        architecture: x64

    - name: Make gradlew executable
      run: chmod +x ./build.sh

    - name: build jar
      run: bash ./build.sh

    - name: Upload artifacts
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.CREATE_RELEASE }}
        tag_name: '${{ inputs.version }}'
        name: 'NBT-${{inputs.version}}'
        files: |
          target/**
