### Author: Frish2021 ###
name: release

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        default: tag
      release-name:
        tag:
          type: string
          default: NBT

jobs:
  build:
    name: Build NBT-jar
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4.5.0
      with: 
        java-version: '22'
        distribution: 'temurin'
        architecture: x64

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: build jar
      run: ./gradlew build

    - name: Upload artifacts
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.CREATE_RELEASE }}
        tag_name: '${{ inputs.tag }}'
        name: '${{ inputs.release-name }}'
        files: build/targets/NBT-2.0.1.jar
