### Author: Frish2021 ###
name: release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string

env:
  version: 2.0.2

jobs:
  build:
    name: Build NBT-jar
    runs-on: ubuntu-latest

    env:
      name: 'NBT-${{ inputs.version }}'

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4.5.0
      with: 
        java-version: '22'
        distribution: 'temurin'
        architecture: x64

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: build jar
      run: ./gradlew build

    - name: Upload artifacts
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.CREATE_RELEASE }}
        tag_name: '${{ inputs.version }}'
        name: '$name'
        files: 'build/targets/$name.jar'
