# This is a basic workflow that is manually triggered

name: release

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      tag:
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build:
    name: Build NBT-jar
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4.5.0
      with: 
        java-version: '22'
        distribution: 'temurin'
        architecture: x64

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: build jar
      run: ./gradlew build

    - name: Upload artifacts
      uses: softprops/action-gh-release@v2
      with:
        tag_name: '${{ tag }}'
        name: NBT-1.0.0
        files: build/libs/NBT-1.0.0.jar
